apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeAutoscaler
metadata:
  name: test-pva
  namespace: monitoring
spec:
  increaseBy: 10%
  threshold: 50%
  maxCapacity: 10Gi
  targetRef:
    kind: Prometheus
    apiVersion: monitoring.coreos.com/v1
    name: k8s
    namespace: monitoring