apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeAutoscaler
metadata:
  name: test-pva
spec:
  targetRef:
    kind: StatefulSet
    apiVersion: apps/v1
    name: test-sts
  # updatePolicy:
  #   updateMode: {offline|online}
  #   minReplicas: 1
  pvcPolicy:
  - name: data-lvm1
    increaseBy: 10% # in vpa this is specified as a flag to the recommender binary
    threshold: 25% # in vpa this is equivalent to upper and lower bound
    maxCapacity: 10Gi
  - name: data-lvm2
    increaseBy: 20% # in vpa this is specified as a flag to the recommender binary
    threshold: 20% # in vpa this is equivalent to upper and lower bound
    maxCapacity: 5Gi
  - name: data-lvm3
    increaseBy: 20% # in vpa this is specified as a flag to the recommender binary
    threshold: 20% # in vpa this is equivalent to upper and lower bound
    maxCapacity: 5Gi
status:
  lastError:
    lastTransitionTime: "2025-06-04T10:08:59Z"
    lastUpdateTime: "2025-06-04T10:08:59Z"
    message: |
      Could not resize all PVCs:
        - data-lvm2-test-sts-1: Some random ratelimit error asdf
        - data-lvm2-test-sts-0: Resize timeout
  conditions:
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    lastUpdateTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizeInProgress
    message: |
      The following PVCs are being resized:
        - data-lvm2-test-sts-1
        - data-lvm2-test-sts-0
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    lastUpdateTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizePending
    message: |
      Resize is pending for the following PVCs:
        - data-lvm2-test-sts-0
        - data-lvm2-test-sts-1
  pvcs:
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm1-test-sts-0
    newSize: "0"
    prevSize: "0"
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm1-test-sts-1
    newSize: "0"
    prevSize: "0"
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 2.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm2-test-sts-0
    newSize: "0"
    prevSize: "0"
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 10.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm2-test-sts-1
    newSize: "0"
    prevSize: "0"
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm3-test-sts-0
    newSize: "2Gi"
    prevSize: "1Gi"
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm3-test-sts1
    newSize: "2Gi"
    prevSize: "1Gi"

---

apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeAutoscaler
metadata:
  name: test-pva
spec:
  targetRef:
    kind: PersistentVolumeClaim
    apiVersion: v1
    name: data-lvm2-test-sts-1
  # updatePolicy:
  #   updateMode: {offline|online}
  #   minReplicas: 1
  # pvcPolicy:
  # - pvcTemplateName: pvc-1
  #   increaseBy: 10% # in vpa this is specified as a flag to the recommender binary
  #   threshold: 50% # in vpa this is equivalent to upper and lower bound
  #   maxCapacity: 10Gi
status:
  lastError:
    lastTransitionTime: "2025-06-04T10:08:59Z"
    lastUpdateTime: "2025-06-04T10:08:59Z"
    message: |
      Could not resize PVCs:
        - data-lvm2-test-sts-1
      asdf ratelimit error asdf
  conditions:
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizeInProgress
    message: |
    The following PVCs are being resized:
      - data-lvm2-test-sts-1
      - data-lvm2-test-sts-0
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizePending
    message: |
    Resize is pending for the following PVCs:
      - data-lvm0-test-sts-1
      - data-lvm3-test-sts-1
  pvcs:
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm2-test-sts-2
    newSize: "0"
    prevSize: "0"

---

apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeAutoscaler
metadata:
  name: test-pva
spec:
  targetRef:
    kind: StatefulSet
    apiVersion: apps/v1
    name: some-sts
  increaseBy: 10% # in vpa this is specified as a flag to the recommender binary
  threshold: 50% # in vpa this is equivalent to upper and lower bound
  maxCapacity: 10Gi
  # updatePolicy:
  #   updateMode: {offline|online}
  #   minReplicas: 1
  # pvcPolicy:
  # - pvcTemplateName: pvc-1
  #   increaseBy: 10% # in vpa this is specified as a flag to the recommender binary
  #   threshold: 50% # in vpa this is equivalent to upper and lower bound
  #   maxCapacity: 10Gi
status:
  lastError:
    lastTransitionTime: "2025-06-04T10:08:59Z"
    lastUpdateTime: "2025-06-04T10:08:59Z"
    message: |
      Could not resize PVCs:
        - data-lvm2-test-sts-1
      asdf ratelimit error asdf
  conditions:
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizeInProgress
    message: |
    The following PVCs are being resized:
      - data-lvm2-test-sts-1
      - data-lvm2-test-sts-0
  - lastTransitionTime: "2025-06-04T10:08:59Z"
    status: "True"
    type: ResizePending
    message: |
    Resize is pending for the following PVCs:
      - data-lvm0-test-sts-1
      - data-lvm3-test-sts-1
  pvcs:
  - freeInodesPercentage: 99.96%
    freeSpacePercentage: 97.72%
    lastCheck: "2025-07-23T13:39:24Z"
    name: data-lvm2-test-sts-2
    newSize: "0"
    prevSize: "0"

