apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeAutoscaler
metadata:
  name: test-pva
spec:
  increaseBy: 10%
  threshold: 50%
  maxCapacity: 10Gi
  targetRef:
    kind: StatefulSet
    apiVersion: apps/v1
    name: test-sts
    namespace: default