apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeClaimAutoscaler
metadata:
  name: test-pvca
spec:
  increaseBy: 10%
  threshold: 50%
  maxCapacity: 10Gi
  scaleTargetRef:
    name: data-lvm-test-sts-0