resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: europe-docker.pkg.dev/gardener-project/releases/gardener/pvc-autoscaler
  newTag: v0.1.3-dev-5b4b5cb-dirty
