events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        # Serve static fake Prometheus metrics from file
        location /metrics {
            add_header Content-Type text/plain;
            alias /var/metrics/metrics.txt;
        }

        # Health check endpoint
        location /health {
            add_header Content-Type text/plain;
            return 200 'OK';
        }
    }
}